# Generated by Django 4.1 on 2022-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_client_detsale_product_sale_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome'),
        ),
    ]
